---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: "git@github.com:hjtenklooster/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_files:
  - .osx
#  - .zshrc
#  - .gitignore
#  - .inputrc
#  - .vimrc

homebrew_installed_packages:
# - ansible # Installed via Pip.
  - autoconf
  - bash
  - binutils
  - blackhole-2ch
  - cmake
  - coreutils
  - coreutils
  - diffutils
  - ed
  - ffmpeg
  - findutils
  - findutils
  - flex
  - gawk
  - gnu-indent
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gpatch
  - grep
  - gzip
  - less
  - libarchive
  - m4
  - make
  - nano
  - screen
  - tmux
  - watch
  - wdiff
  - wget
  - whisper-cpp
  - yt-dlp
  - zip

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - adguard
  - adobe-creative-cloud
  - appcleaner
  - betterdisplay
  - chatgpt
  - fork
  - google-chrome
  - jump-desktop-connect
  - karabiner-elements
  - readdle-spark
  - utm

#  - chromedriver
#  - docker
#  - dropbox
#  - firefox
#  - google-chrome
#  - handbrake
#  - licecap
#  - sequel-ace
#  - slack
#  - sublime-text
#  - transmit

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - ane_transformers
  - openai-whisper
  - coremltools
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

#list of bash scripts to run
bash_scripts: 
  - "~/src/dotfiles/configure_dotfiles.sh"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: 
  - "tasks/run_bash_scripts.yml"
